version: "3.9"
services:
  geosint:
    build:
      context: .
      args:
        - MAPS_API_KEY=${MAPS_API_KEY}
    env_file:
      - .env
    command: ["pm2-runtime", "ecosystem.config.js"]
    container_name: geosint
    hostname: geosint
    restart: always
    volumes:
      - "./challenges.yml:/usr/src/app/challenges.yml"
      - "./app/public/:/usr/src/app/public/"
    ports:
      - "5000:6958"